# Travis CI config, for https://travis-ci.org/denny/ShinyCMS-ruby

dist: bionic

language: ruby

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0

cache: bundler

addons:
  postgresql: "10"

before_install:
  - gem install bundler

before_script:
  - bundle exec rails assets:precompile
  - bundle exec rails db:create
  - bundle exec rails db:schema:load

script:
  - bundle exec rspec
